name: CI

on:
  pull_request:
    branches: ["*"]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  backend-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Build backend
        run: dotnet build RePlay.sln -c Release

      # - name: Test + collect coverage
      #   run: |
      #     dotnet-coverage collect \
      #       --output-format cobertura \
      #       -o coverage-pr.cobertura.xml \
      #       "dotnet test -c Release --no-build --collect:none"

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-pr
      #     path: coverage-pr.cobertura.xml